#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: Phase 0 — deploy LineBot-CRM ตาม README
# ค่าทั้งหมดบันทึกใน .env (อยู่ใน .gitignore) รันซ้ำได้ ค่าที่เคยกรอกจะถูกเสนอเป็นค่าเริ่มต้น
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# clip "text" คัดลอกลงคลิปบอร์ด (ถ้าทำได้) เพื่อให้วางใน Script Properties ได้ทันที
clip() {
  if   command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  elif command -v pbcopy   >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v xclip    >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  else return 1; fi
}

# copy_prop KEY VALUE: คัดลอกค่าลงคลิปบอร์ดแล้วรอให้วางใน Script Properties
copy_prop() {
  if clip "$2"; then
    printf '  %s•%s %s%s%s คัดลอกลงคลิปบอร์ดแล้ว → วางในช่อง Value แล้วกด Enter ' "$BLUE" "$RESET" "$BOLD" "$1" "$RESET"
  else
    printf '  %s•%s %s%s%s = %s (กด Enter เมื่อวางแล้ว) ' "$BLUE" "$RESET" "$BOLD" "$1" "$RESET" "$2"
  fi
  read -r _ || true
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

banner "LineBot-CRM · Phase 0 — deploy ระบบเดิมตาม README"

# ── 1. เครื่องมือ + clasp login ───────────────────────────────────────────
stage "เตรียมเครื่องมือและล็อกอิน clasp"
command -v node >/dev/null 2>&1 || { warn "ไม่พบ node"; exit 1; }
command -v clasp >/dev/null 2>&1 || { warn "ไม่พบ clasp (npm install -g @google/clasp)"; exit 1; }
say "node $(node --version), clasp $(clasp --version)"
say "clasp ต้องเปิด Apps Script API ในบัญชี Google ก่อน:"
open_url "https://script.google.com/home/usersettings"
step "เปิดสวิตช์ 'Google Apps Script API' เป็น On (ใช้บัญชี hallowsman@gmail.com)"
pause "เปิดแล้วกด Enter"
if clasp show-authorized-user 2>&1 | grep -qiE "logged in as|authorized as|@"; then
  say "clasp ล็อกอินอยู่แล้ว: $(clasp show-authorized-user 2>&1 | head -n1)"
else
  step "กำลังเปิดหน้าล็อกอินของ clasp เลือกบัญชี hallowsman@gmail.com แล้วกดอนุญาต"
  clasp login
fi

# ── 2. Messaging API channel ─────────────────────────────────────────────
stage "LINE Messaging API: token และ userId ของแอดมิน"
open_url "https://developers.line.biz/console/"
step "เลือก Provider → เลือก Messaging API channel ของ OA ที่จะใช้"
step "แท็บ 'Messaging API' → เลื่อนลงหา 'Channel access token (long-lived)' → Issue/Copy"
ask_secret LINE_CHANNEL_ACCESS_TOKEN "วาง Channel access token:"
step "แท็บ 'Basic settings' → เลื่อนลงหา 'Your user ID' (ขึ้นต้นด้วย U) → Copy"
note "นี่คือ LINE userId ของคุณ จะเป็นแอดมินคนแรกของระบบ"
ask BOOTSTRAP_ADMIN_USER_ID "วาง Your user ID:"
[[ "$BOOTSTRAP_ADMIN_USER_ID" =~ ^U[0-9a-f]{32}$ ]] || warn "รูปแบบไม่ตรง (ควรเป็น U ตามด้วยเลขฐาน 16 จำนวน 32 ตัว) ตรวจอีกครั้งหากยังไม่แน่ใจ"
write_env LINE_CHANNEL_ACCESS_TOKEN "$LINE_CHANNEL_ACCESS_TOKEN"
write_env BOOTSTRAP_ADMIN_USER_ID "$BOOTSTRAP_ADMIN_USER_ID"

# ── 3. LINE Login channel ────────────────────────────────────────────────
stage "LINE Login channel (Provider เดียวกัน)"
say "ต้องอยู่ใน Provider เดียวกับ Messaging API channel เพื่อให้ userId ตรงกัน"
open_url "https://developers.line.biz/console/"
step "เข้า Provider เดิม → Create a new channel → เลือก 'LINE Login'"
step "Region: Thailand, App types: ติ๊ก 'Web app', ตั้งชื่อเช่น 'LineBot-CRM Login'"
step "หลังสร้าง แท็บ 'Basic settings' → คัดลอก 'Channel ID' (ตัวเลข 10 หลัก)"
ask LINE_LOGIN_CHANNEL_ID "วาง Channel ID:"
[[ "$LINE_LOGIN_CHANNEL_ID" =~ ^[0-9]+$ ]] || warn "Channel ID ควรเป็นตัวเลขล้วน"
write_env LINE_LOGIN_CHANNEL_ID "$LINE_LOGIN_CHANNEL_ID"

# ── 4. Netlify ───────────────────────────────────────────────────────────
stage "Netlify: สร้างเว็บ (ยังใช้ config ชั่วคราว)"
say "ต้องได้โดเมนก่อน เพราะ LIFF ต้องระบุ Endpoint URL"
open_url "https://app.netlify.com/drop"
step "ลากโฟลเดอร์ frontend ไปวาง (อยู่ที่ $ROOT_DIR/frontend)"
step "รอ deploy เสร็จ แล้วคัดลอกโดเมน เช่น https://xxxx.netlify.app"
note "เปลี่ยนชื่อไซต์ได้ที่ Site configuration → Change site name"
ask NETLIFY_URL "วาง URL ของเว็บ:"
NETLIFY_URL="${NETLIFY_URL%/}"
[[ "$NETLIFY_URL" =~ ^https:// ]] || warn "URL ควรขึ้นต้นด้วย https://"
write_env NETLIFY_URL "$NETLIFY_URL"

# ── 5. LIFF ×2 ───────────────────────────────────────────────────────────
stage "LIFF app 2 ตัว (สมาชิก + เจ้าหน้าที่)"
open_url "https://developers.line.biz/console/"
step "เปิด LINE Login channel ที่เพิ่งสร้าง → แท็บ 'LIFF' → Add"
step "ตัวที่ 1 (สมาชิก): Size: Full | Endpoint URL: $NETLIFY_URL/ | Scope: ติ๊ก profile และ openid"
ask LIFF_ID_MEMBER "วาง LIFF ID ของสมาชิก (รูปแบบ 1234567890-AbCdEfGh):"
step "ตัวที่ 2 (เจ้าหน้าที่): Size: Full | Endpoint URL: $NETLIFY_URL/admin/ | Scope: profile และ openid"
ask LIFF_ID_ADMIN "วาง LIFF ID ของเจ้าหน้าที่:"
warn "LINE Login channel ที่ยังเป็นสถานะ Developing ใช้ได้เฉพาะแอดมิน/tester ของ channel"
note "เพิ่มเจ้าหน้าที่ทดสอบที่แท็บ 'Roles' และก่อนเปิดให้สมาชิกจริง ต้องกด Publish channel"
write_env LIFF_ID_MEMBER "$LIFF_ID_MEMBER"
write_env LIFF_ID_ADMIN "$LIFF_ID_ADMIN"

# ── 6. clasp create + push ───────────────────────────────────────────────
stage "สร้างโปรเจกต์ Apps Script และ push โค้ด"
cd "$ROOT_DIR/backend"
if [[ -f .clasp.json ]]; then
  say "พบ .clasp.json อยู่แล้ว ข้ามการสร้างโปรเจกต์ใหม่"
else
  say "กำลังรัน: clasp create --type webapp --title LineBot-CRM --rootDir ."
  clasp create --type webapp --title "LineBot-CRM" --rootDir .
fi
say "กำลังรัน: clasp push -f"
clasp push -f
cd "$ROOT_DIR"

# ── 7. Script Properties + setupSchema ───────────────────────────────────
stage "ตั้งค่า Script Properties และสร้างฐานข้อมูล"
WEBHOOK_TOKEN=$(_existing WEBHOOK_TOKEN || true)
if [[ -z "$WEBHOOK_TOKEN" ]]; then
  if command -v openssl >/dev/null 2>&1; then WEBHOOK_TOKEN=$(openssl rand -hex 24)
  else WEBHOOK_TOKEN=$(head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'); fi
fi
write_env WEBHOOK_TOKEN "$WEBHOOK_TOKEN"
( cd backend && clasp open-script ) || true
step "Apps Script → ⚙ Project Settings → เลื่อนลง 'Script Properties' → Edit script properties → Add"
say "เพิ่มทีละคีย์ (wizard จะคัดลอกค่าลงคลิปบอร์ดให้ทีละตัว):"
copy_prop LINE_CHANNEL_ACCESS_TOKEN "$LINE_CHANNEL_ACCESS_TOKEN"
copy_prop LINE_LOGIN_CHANNEL_ID "$LINE_LOGIN_CHANNEL_ID"
copy_prop WEBHOOK_TOKEN "$WEBHOOK_TOKEN"
copy_prop BOOTSTRAP_ADMIN_USER_ID "$BOOTSTRAP_ADMIN_USER_ID"
copy_prop LIFF_MEMBER_URL "https://liff.line.me/$LIFF_ID_MEMBER"
step "กด Save script properties"
pause "บันทึกแล้วกด Enter"
step "กลับหน้า Editor → เลือกฟังก์ชัน setupSchema → Run → กดอนุญาตสิทธิ์ (Advanced → Go to ... → Allow)"
step "ดู Execution log ต้องมีบรรทัด 'Created spreadsheet: ...' (นั่นคือ Google Sheet ฐานข้อมูล)"
pause "setupSchema รันสำเร็จแล้วกด Enter"
step "เลือกฟังก์ชัน checkConfig → Run → ต้องไม่มีคีย์ขาด"
pause "checkConfig ผ่านแล้วกด Enter"

# ── 8. Deploy web app ────────────────────────────────────────────────────
stage "Deploy เป็น Web app"
( cd backend && clasp open-script ) || true
step "มุมขวาบน Deploy → New deployment → ไอคอนเฟือง → Web app"
step "Execute as: Me | Who has access: Anyone → Deploy"
step "คัดลอก Web app URL (ลงท้าย /exec)"
warn "ห้ามสร้าง deployment ใหม่ทุกครั้งที่แก้โค้ด ไม่งั้น URL เปลี่ยน: ใช้ Manage deployments → ✏️ → New version"
ask API_BASE "วาง URL ที่ลงท้าย /exec:"
[[ "$API_BASE" =~ /exec$ ]] || warn "URL ควรลงท้ายด้วย /exec"
write_env API_BASE "$API_BASE"

# ── 9. config.js + deploy Netlify อีกครั้ง ────────────────────────────────
stage "ใส่ค่าใน frontend/assets/config.js แล้ว deploy ใหม่"
cat > frontend/assets/config.js <<CFG
// แก้ค่าเหล่านี้หลัง deploy Apps Script และสร้าง LIFF แล้ว (ไม่ใช่ความลับ — ค่าพวกนี้เห็นได้ฝั่ง client อยู่แล้ว)
window.APP_CONFIG = {
  API_BASE: '$API_BASE',   // URL ที่ลงท้าย /exec
  LIFF_ID_MEMBER: '$LIFF_ID_MEMBER',      // LIFF ของหน้าสมาชิก (Endpoint = https://<โดเมน>/)
  LIFF_ID_ADMIN: '$LIFF_ID_ADMIN'         // LIFF ของหน้าเจ้าหน้าที่ (Endpoint = https://<โดเมน>/admin/)
};
CFG
say "✓ เขียน frontend/assets/config.js แล้ว"
open_url "https://app.netlify.com/"
step "เปิดไซต์ที่สร้างไว้ → แท็บ 'Deploys' → ลากโฟลเดอร์ frontend ไปวางในกล่อง 'Drag and drop' อีกครั้ง"
pause "deploy เสร็จแล้วกด Enter"

# ── 10. Webhook ──────────────────────────────────────────────────────────
stage "ตั้ง Webhook ที่ LINE Messaging API"
WEBHOOK_URL="${API_BASE}?wh=${WEBHOOK_TOKEN}"
if clip "$WEBHOOK_URL"; then say "คัดลอก Webhook URL ลงคลิปบอร์ดแล้ว"; else say "Webhook URL: $WEBHOOK_URL"; fi
open_url "https://developers.line.biz/console/"
step "Messaging API channel → แท็บ 'Messaging API' → Webhook URL → Edit → วาง → Update"
step "กด Verify (ควรขึ้น Success) → เปิด 'Use webhook'"
step "ปิด 'Auto-reply messages' และ 'Greeting messages' ที่ LINE Official Account Manager (Response settings)"
warn "Webhook URL มีโทเค็นลับ อย่าแชร์หรือ commit"
pause "ตั้งค่าเสร็จแล้วกด Enter"

finish
say "ทดสอบเฟส 0: เปิด https://liff.line.me/$LIFF_ID_ADMIN ในแอป LINE (ในฐานะแอดมิน)"
say "และแอด OA แล้วพิมพ์ 'สถานะ' เพื่อดูว่า webhook ตอบกลับ"
